server:
  port: 17928

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    port: 6379
    host: 124.222.96.147
    database: 0
    timeout: 5000
    password: whatever

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.96.147:3306/vegetables?useUnicode=true&characterEncoding=utf-8
    username: vegetables
    password: vegetables0928..
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  configuration:
    log-impl: com.example.vegetables.config.LogStdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1

# 日志配置
logging:
  level:
    com.example.vegetables: info
    org.springframework: info

